default: &default
  adapter: postgresql
  username: aelaa
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bigboss_development

test:
  <<: *default
  database: bigboss_test

production:
  <<: *default
  database: bigboss
